# Generated by Django 3.2.5 on 2021-07-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='Título')),
                ('descricao', models.TextField(max_length=100, verbose_name='Descrição')),
                ('url', models.URLField(verbose_name='url')),
            ],
        ),
    ]
