# Generated by Django 3.2.5 on 2021-07-28 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categoriaID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.categorias'),
        ),
    ]
